### ISSUE TITLE
Change mentions of SublimeText to Atom?

### ISSUE THREAD

**Issue by kfrn** [dev-academy-programme/curriculum#105]
[This tutorial](https://github.com/dev-academy-programme/curriculum/tree/master/resources/github-phase-0-workflow-TUTORIAL) on using github references Sublime, can I edit it to refer to Atom?

**Comment by richchurcher** [comment]
Yeah, I did a pass through the docs changing references but this one was so embedded (all screenshots are of Sublime) that I shelved it until I had time to come up with a better update.

One termporary alternative might be to say, "This tutorial refers to the Sublime editor, but we now recommend and support Atom." I suspect it might be confusing to refer to Atom but show screenshots of Sublime!

**Comment by kfrn** [comment]
Indeed! I added that note and opened a Pull Request. Thanks Rich.

**Comment by kfrn** [comment]
Now resolved. :)

**Comment by richchurcher** [comment]
Oh yeah totally forgot to put #closes on the commit :)
