### ISSUE TITLE
Double quotes throwing error for echo command

### ISSUE THREAD

**Issue by DanBlakeNZ** [dev-academy-programme/curriculum#109]
For the assignment "Publish a user site on GitHub" the instructions say to use the following code:
`echo "Kia ora ao mārama (hello world!)" > index.html`

However this throw's a zsh error. Use single quotes ' ' worked for me rather than than double quotes " ". So it should be:

`echo 'Kia ora ao mārama (hello world!)' > index.html`

**Comment by richchurcher** [comment]
Hi @DanBlakeNZ :) I can't reproduce your error: can you do a `zsh --version` for me? Also copy/paste the output you get when you attempt to use the above command. Double quotes should be fine.

**Comment by DanBlakeNZ** [comment]
Hey @richchurcher 

Sure thing, zsh version: zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

Here is the copy of the input and resulting zsh error:

`echo "Kia ora ao mārama (hello world!)" > index.html`
which results in the following:
`zsh: event not found: )`

but works fine when I use:
 `echo 'Kia ora ao mārama (hello world!)' > index.html`

Other people have said they are getting the same error, but using the single brackets fixes it for them.

**Comment by richchurcher** [comment]
Ah yeah, it's the exclamation point, which does history expansion... didn't notice that! Thanks :)

**Comment by DanBlakeNZ** [comment]
No worries, glad to help!
