### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mike-keogh** [dev-academy-programme/curriculum#110]
The search inside yourself is broken.

**Comment by don-smith** [comment]
Thanks Mike! Would you be able to provide a link to the page that has the broken link? Much appreciated!

**Comment by mike-keogh** [comment]
Hey Don! This email got lost in my unorganised mail I apologise for the
late reply, here is the link
https://github.com/dev-academy-programme/curriculum/tree/master/concepts/nt-emotional-intelligence

**Comment by don-smith** [comment]
All good. Thanks Mike!
