### ISSUE TITLE
Broken link in 'Time and Habit' Management Resources

### ISSUE THREAD

**Issue by zachmandeville** [dev-academy-programme/curriculum#111]
**Summary**
In the README for **Time and Habit Management Resources** (part of phase 0/task 1.3), there is a link for "Timeboxes" that leads to a 404 page.

**Details**
The url for the README is here:
`https://github.com/dev-academy-programme/curriculum/blob/master/resources/nt-time-ARTICLE/README.md`
The relevant link is "Timebox" at the bottom, which leads to a 404 page at `https://www.agilealliance.org/guide/timebox`

This may be due to agilealliance.org changing their directory name from guide to glossary.   When I searched `site:agilealliance.org timebox` the first result was `https://www.agilealliance.org/glossary/timebox/` which provides a nice, short article on the technique.

**Comment by don-smith** [comment]
@zachmandeville, thank you for helping us keep the curriculum current. It looks like the agilealliance website changed their folder name from `guide` to `glossary`. Should be fixed now.
